version: '3.9'
services: 
  mysql:
    image: mysql
    command: --lower_case_table_names=0 --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: estoqueDb
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: K[u}7YgkwZ
      MYSQL_PASSWORD: K[u}7YgkwZ
